<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\JeetDonga_Practical.BLL\JeetDonga_Practical.BLL.csproj" />
		<ProjectReference Include="..\JeetDonga_Practical.DAL\JeetDonga_Practical.DAL.csproj" />
	</ItemGroup>

</Project>
